### ISSUE TITLE
Could not compile dependency :ex_secp256k1

### ISSUE THREAD

**Issue by vbaranov** [izelnakri/eth#46]
The current master branch from commit https://github.com/izelnakri/eth/commit/213c8a4527abd9eaaa43aa2c26fa0f163b2b508d

System spec:
Mac OS
Elixir version: `Elixir 1.11.4 (compiled with Erlang/OTP 23)`
Erlang/OTP version: `Erlang/OTP 23 [erts-11.2.2.1]`

```
    Updating crates.io index
error: failed to select a version for the requirement `crypto-mac = "^0.7"`
candidate versions found which didn't match: 0.11.1, 0.11.0, 0.10.1, ...
location searched: crates.io index
required by package `hmac v0.7.0`
    ... which is depended on by `hmac-drbg v0.2.0`
    ... which is depended on by `libsecp256k1 v0.3.5`
    ... which is depended on by `exsecp256k1 v0.1.0 (/Users/barrakuda/Documents/code/eth/deps/ex_secp256k1/native/exsecp256k1)`
could not compile dependency :ex_secp256k1, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_secp256k1", update it with "mix deps.update ex_secp256k1" or clean it with "mix deps.clean ex_secp256k1"
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:68: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
    (rustler 0.21.1) lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.11.4) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
```

**Comment by izelnakri** [comment]
Hi @vbaranov , I just updated `libsecp256k1` dependency on`eth@0.6.2`. Let me know if the dependency compilation is still broken.
